### ISSUE TITLE
exemples de métadonnées pour Nakala

### ISSUE THREAD

**Issue by Lucaterre** [chartes/Nakalator#2]
## ENCPOS

```
name: ENCPOS_1854_08
data:
  path: /Users/lucaterre/Documents/pro/ENC-tools/Nakalator/nakalator_workspace/data/ENCPOS_1854/ENCPOS_1854_08
  type: tif
  status: pending
collectionsIds: 10.34847/nkl.b2118d30
collectionTitle: ENCPOS_1854
collectionDescription: Les positions des thèses de l'Ecole nationale des chartes de
  1854
collectionStatus: private
metadata:
  http://nakala.fr/terms#title:
    value: ENCPOS_1854_08
    lang: fr
    typeUri: http://www.w3.org/2001/XMLSchema#string
  http://purl.org/dc/terms/description:
    value: Essai sur les variations des limites géographiques et de la constitution
      politique de l’Aquitaine, depuis César jusqu’à l’an 613
    lang: fr
    typeUri: http://www.w3.org/2001/XMLSchema#string
  http://nakala.fr/terms#creator:
    value:
      givenname: Félix
      surname: Rocquain De Courtemblay
  http://purl.org/dc/terms/extent:
    value: 27-28
    lang: fr
    typeUri: http://www.w3.org/2001/XMLSchema#string
  http://purl.org/dc/terms/date:
    value: '1854'
    lang: fr
    typeUri: http://www.w3.org/2001/XMLSchema#string
```

## Bellelay

```
name: bellelay
data:
  path: /Users/lucaterre/Documents/pro/ENC-tools/Nakalator/nakalator_workspace/data/bellelay
  type: jpeg
  status: pending
collectionIds: ''
collectionTitle: Bellelay test
collectionDescription: ceci est une collection pour les images de bellelay
collectionStatus: private
collectionsIds: 10.34847/nkl.56bdg0ao
metadata:
  http://nakala.fr/terms#title:
    value: Images du graduel de Bellelay
    lang: fr
    typeUri: http://www.w3.org/2001/XMLSchema#string
  http://purl.org/dc/terms/description:
    value: Le graduel de Bellelay est l'un des premiers livres liturgiques notés de
      l'ordre des Prémontrés. Il contient tout le répertoire des messes et des offices
      pour le cycle liturgique de l'année, plus quelques ajouts marginaux (compositions
      musicales, donation).
    lang: fr
    typeUri: http://www.w3.org/2001/XMLSchema#string
```

## Exemple général

```
# ***************************************************************************
# FICHIER D'EXEMPLE POUR LA CRÉATION DE MÉTADONNÉES                         *
# NE PAS SUPPRIMER CE FICHIER                                               *
# UTILISER CE FICHIER COMME MODÈLE POUR CRÉER DE NOUVELLES MÉTADONNÉES      *
# ***************************************************************************


name: "ENCPOS_1851" # Nom du projet (de préférence le préfixe utilisé pour les images)

data:
  path: "" # Chemin absolu vers le répertoire des données dans data/ par exemple (images)
  type: "jpeg" # Format des images (jpeg, tiff, png, etc.)
  status: "pending" # "pending" ou "published". Il est conseillé de laisser "pending" par défaut et de changer le status dans Nakala une fois le dépôt validé.


collectionsIds: "" # utiliser le DOI de la collection Nakala si les images sont déposées dans une collection, sinon laisser vide.

metadata:
  # Certaines métadonnées sont générés automtiquement depuis lib/constants.py (METADATA_AUTO)

  # Métadonnées strictement requises (à compléter manuellement):
  http://nakala.fr/terms#title:
    value : "Images du graduel de Bellelay"
    lang : "fr"
    typeUri: "http://www.w3.org/2001/XMLSchema#string"
  http://purl.org/dc/terms/description:
    value: "Le graduel de Bellelay est l'un des premiers livres liturgiques notés de l'ordre des Prémontrés. Il contient tout le répertoire des messes et des offices pour le cycle liturgique de l'année, plus quelques ajouts marginaux (compositions musicales, donation)."
    lang: "fr"
    typeUri: "http://www.w3.org/2001/XMLSchema#string"

  # ... ajouter d'autres métadonnées si nécessaire avec d'autres schémas, par exemple:
  # http://purl.org/dc/terms/creator:
  # http://purl.org/dc/terms/contributor:
  # http://purl.org/dc/terms/language:
  # http://purl.org/dc/terms/relation:
  # http://purl.org/dc/terms/rightsHolder:
  # http://purl.org/dc/terms/spatial:
  # http://purl.org/dc/terms/available:
  # http://purl.org/dc/terms/modified:
  # http://purl.org/dc/terms/rights:
  # http://purl.org/dc/terms/isVersionOf:
  # http://purl.org/dc/terms/format:
  # http://purl.org/dc/terms/bibliographicCitation:
  # http://purl.org/dc/terms/abstract:
  # http://purl.org/dc/terms/source:
  # http://purl.org/dc/terms/subject:
  # http://purl.org/dc/terms/medium:
  # ...

```
